#Different level layouts

level1_map = [
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "x                     x",
    "x g                   x",
    "xxxxxxxx              x",
    "xxxxxxxx    ~~        x",
    "xxxxxxxxxxxxxxxxxxx   x",
    "xxxx                  x",
    "xxxx                  x",
    "xbbb    c             x",
    "xblb   xxx      xxxxxxx",
    "xbbbxxxxxxxxxxxxxxxxxxx",
    "xbbbbbbbbbbbbbbbx     x",
    "xbbbbbbbbbbbbbbbb     x",
    "xbbbbbbbbbbbbbbbb     x",
    "xbbbbbbbbbbbbbbbx     x",
    "xxxxxxxxxxxxxxxxx     x",
    "x       bbx           x",
    "x       xlx          xx",
    "x       xbx           x",
    "x       xbb   ~       x",
    "x    xxxxxxxxxx       x",
    "x             x   xx  x",
    "x             x   xx  x",
    "x             x   xx  x",
    "x             x   xx  x",
    "xxxx          x   xx  x",
    "xxxx          x^^^xx^^x",
    "xxxx          xxxxxxxxx",
    "xxxx     xxx          x",
    "xxxx     vb           x",
    "xxxx      b           x",
    "xxxx      l           x",
    "xxxx      b           x",
    "xxxxxx    b           x",
    "xxxxxx^^  b           x",
    "xxxxxxxxxxxxxxxxxx    x",
    "xxxxxxxxxxxxxx   v    x",
    "xxxxxxxxxxxxxx        x",
    "xxxxxxxxxxxxxx      xxx",
    "xxxxxxxxxxxxxx      xxx",
    "xxxxxxxxxxxxxx      xxx",
    "x                   xxx",
    "x                   xxx",
    "x                xxxxxx",
    "x                     x",
    "x                     x",
    "x       ~ ^           x",
    "x      xxxxxxx        x",
    "x        bbb          x",
    "x        blb          x",
    "xxxx     bbb          x",
    "x        blb          x",
    "x        bbb          x",
    "x        bbb          x",
    "x       xxxxxxxx      x",
    "x       x      v      x",
    "x       x             x",
    "x^^^^^^^x             x",
    "xxxxxxxxx        xxxxxx",
    "xxxxxxxxx     xxxxxxxxx",
    "xvv           xxxxxxxxx",
    "x             bblxxxxxx",
    "x    xx  ~  ^^bbbxxxxxx",
    "x    xxxxxxxxxxxxxxxxxx",
    "x    vv             0 x",
    "xxx                   x",
    "xxxxxxxxxxxxx  x  xxxxx",
    "xxxxxxxxxxxxx  x  xxxxx",
    "x   bbbbbbbbb  x  xxxxx",
    "x   bblbblbbxxxx  xxxxx",
    "x   bbbbbbbbxxxx^^xxxxx",
    "x   xxxxxxxxxxxxxxxxxxx",
    "x           xx xx xx xx",
    "x           xx~xx~xx~xx",
    "xxx         xxxxxxxxxxx",
    "xxx         bbb      xx",
    "xxx   ^~    xxx      xx",
    "xxxxxxxxxxxxxxxxxx   xx",
    "x                    xx",
    "x                    xx",
    "x              xxx   xx",
    "x              xxx^^^xx",
    "x    p         xxxxxxxx",
    "x         ~    xxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww"]

level2_map = [
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "xxxx     f  bb        x",
    "xxxx  f     bb        x",
    "xxxx        bb   f    x",
    "xxxxf      ~bb        x",
    "xxxx   g   xxxx      fx",
    "xxxxxxxxx             x",
    "xxxxxxxxx             x",
    "xx f xx               x",
    "xx   xx            xxxx",
    "xxf fxx               x",
    "xx   xx               x",
    "xx f xx     f ~~   f  x",
    "xx~~~xx    xxxxxx     x",
    "xxxxxxx     bxxb ^^^^^x",
    "xxxxxxxbbbxxxxxxxxxxxxx",
    "xx   xxblbblbblbblbblbx",
    "xx   xxbbbbbbbbbbbbbbbx",
    "xx   xxxxxxxxxxxxxxxbbx",
    "xx   xxxxxxxxxxxxxxxbbx",
    "xx   xxblbblbblbblbblbx",
    "xxxxxxxbbbbbbbbbbbbbbbx",
    "xxxxxxxbbbbbbbbbbxxxxxx",
    "x        bbbbbbbbxxxxxx",
    "x        xxxxxxxxxxxxxx",
    "x        x  v         x",
    "x       ~x  f         x",
    "x      xxx            x",
    "x                     x",
    "x xx                  x",
    "x xx                  x",
    "x xx                  x",
    "x^xx        ^         x",
    "xxxxxxxxxxxxxxxxxxx   x",
    "x         f   f       x",
    "x                     x",
    "x                     x",
    "x                   xxx",
    "x                   xxx",
    "x         f ~ f     xxx",
    "x  xxxxxxxxxxxxxxxxxxxx",
    "x  xxxxxxxxxxxxxxxxxxxx",
    "x             xxxxxxxxx",
    "x             xxxxxxxxx",
    "xxx           xxxxxxxxx",
    "x             xxxxxxxxx",
    "x             xxxxxxxxx",
    "x    xxxx             x",
    "x     bb              x",
    "x     bb              x",
    "x  ff bb   xxx        x",
    "x     bb   xxx        x",
    "xxxxxxxxxxxxxxxxxxx   x",
    "xxxxxxxxx     f       x",
    "xxxxxxxxx            xx",
    "xxbbblbbb            xx",
    "xxbbbbbbb  f     f   xx",
    "xxbbblbbb    ~~      xx",
    "xxbbbbbbbxxxxxxxxxxxxxx",
    "xxbbbxxxxxxxxxxxxxxxxxx",
    "xxbbbxxxxxxxxxxxxxxxxxx",
    "xx       v            x",
    "xx                    x",
    "xx                    x",
    "xxxxxxx    f          x",
    "xxxxxxx               x",
    "xxxxxxx^   ~      p   x",
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww"]

level3_map = [
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "x     b      bbb      x",
    "x     b      blb      x",
    "x     b     fbbb      x",
    "x     b      blb W    x",
    "x     l   xxxxxxxx    x",
    "x     x               x",
    "x                     x",
    "x                     x",
    "x                     x",
    "xxxx                  x",
    "xxx                   x",
    "xxx                   x",
    "xxx  s  ~~   ss       x",
    "xxx^^^^^xxx^^^^^xx~   x",
    "xxxxxxxxxxxxxxxxxxxx  x",
    "x                     x",
    "x                ff   x",
    "x                    xx",
    "x                    xx",
    "x                ss  xx",
    "x                    xx",
    "x xxxxxxxxxxxxxxxxxxxxx",
    "x                     x",
    "x                     x",
    "x                     x",
    "x                     x",
    "xx                    x",
    "x                     x",
    "x                     x",
    "x                     x",
    "x       ~             x",
    "xxx     xxxx          x",
    "xxx     xxx           x",
    "xxx     xxx           x",
    "xxxs s sxxx           x",
    "xxx^^^^^xxx ^^        x",
    "xxxxxxxxxxxxxxxxxxxx  x",
    "xxxxxxxxxxxxxxxxxxxx  x",
    "x          v          x",
    "x                     x",
    "x                    xx",
    "x                    xx",
    "x                    xx",
    "x               f    xx",
    "x             xxxxxxxxx",
    "x          f  xxxxxxxxx",
    "x          ^  xxxxxxxxx",
    "x  xxxxxxxxxxxxxxxxxxxx",
    "x  xxxxxxxxxxxxxxxxxxxx",
    "x          f          x",
    "x                     x",
    "xx         f          x",
    "xx            sss     x",
    "xx        ~f          x",
    "xxxxxxxxbxxxxbbxxxxxxbx",
    "xxxxxxxxbbbbbbxxxxxxxbx",
    "xxxxxxxxxxxxxxxxxxxxxbx",
    "xx                  v x",
    "xx                    x",
    "xx                 xxxx",
    "xx              s    xx",
    "xx            x  ~~  xx",
    "xx            xxxxxxxxx",
    "xx            xxxxxxxxx",
    "xx            xxxxxxxxx",
    "xx            xxxxxxxxx",
    "xx      xxx        xxxx",
    "xx      vb         xxxx",
    "xx~      b         xxxx",
    "xxxxx    b         xxxx",
    "xxxxx    b         xxxx",
    "xxxxx    b         blbx",
    "xxxxx  s b         bbbx",
    "xxxxx    b         blbx",
    "xxxxxxxxxxxxxxxxxxxbbbx",
    "xxxxxxxxxxxxxxxxxxxblbx",
    "xxxxx              bbbx",
    "xxxxx              blbx",
    "xxxxx             xxxxx",
    "xxxxx             xxxxx",
    "xxxxx  p    ~    ^xxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww"]

level4_map = [
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxx  00   00 0  xxxxx",
    "xxxxx 000         xxxxx",
    "xxxxx0     00000  xxxxx",
    "xxxxx  p         exxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxx",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "  x                 x  ",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwww"]


#Basic settings that will be true every level
tile_size = 64

screen_width = len(level1_map[0]) * tile_size
screen_height = 1000
fps = 60
gravity = 0.4

